<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '(Không được thiết lập)',
    'An internal server error occurred.' => 'Xảy ra lỗi server',
    'Are you sure you want to delete this item?' => 'Bạn muốn xóa mục này?',
    'Delete' => 'Xóa',
    'Error' => 'Lỗi',
    'File upload failed.' => 'File tải lên không thành công',
    'Home' => 'Trang chủ',
    'Invalid data received for parameter "{param}".' => '"{param}" không hợp lệ',
    'Login Required' => 'Yêu cầu đăng nhập',
    'Missing required arguments: {params}' => 'Thiếu đối số bắt buộc: {params}',
    'Missing required parameters: {params}' => 'Thiếu thông số bắt buộc: {params}',
    'No' => 'Không',
    'No results found.' => 'Không tìm thấy kết quả',
    'Page not found.' => 'Không tìm thấy trang',
    'Please fix the following errors:' => 'Vui lòng sửa lại các lỗi sau:',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => '  Hiển thị từ <b>{begin, number}</b> đến <b>{end, number}</b> trong tổng số <b>{totalCount, number}</b> kết quả',
    'The combination {values} of {attributes} has already been taken.' => '{value} đã được đăng ký',
    'The requested view "{name}" was not found.' => 'Không tìm thấy "{name}"',
    'The verification code is incorrect.' => 'Mã xác minh không chính xác',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Tổng <b>{count}</b> kết quả',
    'Unable to verify your data submission.' => 'Không xác thực được việc truyền dữ liệu',
    'Unknown alias: -{name}' => 'Không xác định được : -{name}',
    'Unknown option: --{name}' => 'Không xác định được tùy chọn: --{name}',
    'Update' => 'Cập nhật',
    'View' => 'Xem chi tiết',
    'Yes' => 'Đồng ý',
    'You are not allowed to perform this action.' => 'Bạn không được phép thực hiện hành động này',
    'the input value' => 'Nhập giá trị',
    '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" đã được sử dụng',
    '{attribute} cannot be blank.' => '{attribute} không được để trống',
    '{attribute} is invalid.' => '{attribute} không hợp lệ',
    '{attribute} is not a valid URL.' => '{attribute} URL không hợp lệ',
    '{attribute} is not a valid email address.' => '{attribute} địa chỉ email không hợp lệ',
    '{attribute} is not in the allowed range.' => '{attribute} không thuộc phạm vi cho phép',
    '{attribute} must be "{requiredValue}".' => '{attribute} phải là "{requiredValue}"',
    '{attribute} must be a number.' => '{attribute} phải là số',
    '{attribute} must be a string.' => '{attribute} phải là một chuỗi kí tự',
    '{attribute} must be an integer.' => '{attribute} phải là số nguyên',
    '{attribute} must be either "{true}" or "{false}".' => '{attribute} phải là "{true}" hoặc "{false}"',
    '{attribute} must be equal to "{compareValueOrAttribute}".' => '{attribute}, {compareValueOrAttribute} không khớp',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => '{attribute} phải lớn hơn "{compareValueOrAttribute}"',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => '{attribute} phải lớn hơn hoặc bằng "{compareValueOrAttribute}"',
    '{attribute} must be less than "{compareValueOrAttribute}".' => '{attribute} phải nhỏ hơn "{compareValueOrAttribute}"',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => '{attribute} phải nhỏ hơn hoặc bằng "{compareValueOrAttribute}"',
    '{attribute} must be no greater than {max}.' => '{attribute} không được lớn hơn {max}',
    '{attribute} must be no less than {min}.' => '{attribute} không được nhỏ hơn {min}',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => '{attribute} không được bằng "{compareValueOrAttribute}"',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '{attribute} phải có ít nhất {min} ký tự',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '{attribute} chỉ tối đa {max} ký tự',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '{attribute} ký tự dài {length} ',
];
